#!/bin/sh

DOCUMENTS_DIR="/var/mobile/Library/Preferences/RJTranslate";
APP_DIR="/Applications/RJTranslate.app";

#   Setting permissiong for writing and executing
chmod 0775 $APP_DIR;
chmod 0755 "/usr/bin/rjparser";
chown root:wheel "/usr/bin/rjparser";

if [ ! -d "$DOCUMENTS_DIR" ]; then
    echo "Creating documents directory..."
    mkdir $DOCUMENTS_DIR
fi

chmod 0777 $DOCUMENTS_DIR;

echo "Cleaning caches..."
uicache

#   tell Cydia to respring
declare -a cydia
cydia=($CYDIA)

if [[ ${CYDIA+@} ]]; then
  eval "echo 'finish:restart' >&${cydia[0]}"
fi

echo "Please, respring your device!"

exit 0
