#!/bin/sh

#   clean caches if package is removing
if [[ $1 == remove ]]; then
    echo "Cleaning caches..."
    uicache;
fi

#   tell Cydia to respring
declare -a cydia;
cydia=($CYDIA);

if [[ ${CYDIA+@} ]]; then
    eval "echo 'finish:restart' >&${cydia[0]}";
fi

if [[ $1 == remove ]]; then
    echo "Please, respring your device!";
fi

exit 0
